### PR TITLE
Added ability to customize number of placeholder items in RecyclerVie…

### PR DESCRIPTION
**Pull request by adamaviner**
Added ability to customize number of placeholder items in RecyclerViewMaterialAdapter, also some grammar in the comments there.

### CODE REVIEW

**Comment by florent37** [comment]
Thanks fort the grammar correction :)
What was tje purpose of a variable place holder item number ? I dont understand

**Comment by adamaviner** [comment]
I'm using a GridLayoutManager with the recycler view, so when I set a span count of 2,
1 item is over the header image because the place holder is hardcoded to 1, but I have 2 items in the first row, as you can see in the top right corner.

screenshot_2015-05-07-00-19-45

With the fix I can call,
new RecyclerViewMaterialAdapter(productAdapter, **2**);
to get the proper behaviour.

**Comment by florent37** [comment]
Oh yes, I forgot this case, good job :)

thanks again for your contribution ! :+1:

**Comment by florent37** [comment]
I sent a new version for you in jcenter, because I already sent a new version today (1.0.2) I didn't want to upload 1.0.3 yes, just for this update. I cadded it 1.0.2.1

`com.github.florent37:materialviewpager:1.0.2.1``

This will be available in the 1.0.3 ;)

**Pull request merged**
