### PR TITLE
Should fix varying toolbar height after scrolling

### PR DESCRIPTION
**Pull request by adamaviner**
Should fix varying toolbar height after scrolling, using scrollMaxDp instead of scrollMax, and changed the toolbar translation calculations

### CODE REVIEW

**Comment by florent37** [comment]
Did you test it ? I have an issue with it, I have a strange behavior with your modification

hammerheadlmy47iflorentchampigny05062015232518

**Comment by adamaviner** [comment]
It works fine for me, I think the problem is that I hardcoded the heights of the status bar and toolbar in 
line 104 : this.scrollMax = settings.headerHeight - **(56 + 24)**;
Probably a bad idea.
Specifically it seems like using the transparent status bar, causes the 24dp of overlap there...
I think I need to measure the actual heights and presence in runtime or something,
not sure how to do that yet.

**Comment by florent37** [comment]
Yes it would be better if you get the real toolbar & status height. (maybe using viewtree observer on toolbar, etc. and http://stackoverflow.com/questions/3407256/height-of-status-bar-in-android)

And don't forget that some devices have transparent statusbar ;)

**Comment by florent37** [comment]
I closed this pull request but send me another when you have a new fix :) And I know you will find a really good fix ! :smile: 

thanks again for your contribution, I really appreciate it :+1:

**Pull request closed without merging**
